import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../components/Landing";
import About from "../components/About";
import Projects from "../components/Projects/Projects";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Who I Even Am</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="container">
      <Landing />
      <About />
      <Projects />
    </div>
    </>
  );
};
 
export default Home;
